peopledoc/vault-cli

.gitignore, setup.cfg, tests/test_vault_api.py, vault_cli/vault_python_api.py
This could occur when user provided an incorrect URL.
=> Avoid an exception when response isn't JSON-formatted

README.md, vault_cli/vault.py
Add:
- `--yaml` option on `set` command
- `--with-key/--without-key` on `get` command
- Display `get a/b/c` in yaml formatted value
=> Vault cli improvements

vault_cli/vault.py, vault_cli/vault_python_api.py
* Respect `verify` parameter even when `REQUESTS_BUNDLE_CA` envvar is defined
* Python 2 compat. It's so easy to do and it will help us to integrate it :)
* Disable the **many** warnings when verify is False
=> Session verify

README.md, vault_cli/vault.py, vault_cli/vault_python_api.py
Now get returns a single value, always. get-all can be used to return multiple values, and explore folders.
=> Changed responsibilities between get and get-all

README.md, vault_cli/vault.py, vault_cli/vault_python_api.py
Add `--token-file` switch/option.
Tested:
```
root@vault:~# VAULT_ADDR=http://127.0.0.1:8200 vault kv put secret/hello value=world # create secret
pilou@laptop:~$ vault -T tokenfile --url http://172.18.0.2:8200 get secret/hello # test short form
--- world
...
pilou@laptop:~$ vault --token-file tokenfile --url http://172.18.0.2:8200 get secret/hello # test long form
--- world
...
pilou@laptop:~$ vault -t plop -T tokenfile --url http://172.18.0.2:8200 get secret/hello # test switch precedence
--- world
...
pilou@laptop:~$ vault --token-file /not/existing/path --url http://172.18.0.2:8200 get secret/hello # test non existing path
Usage: vault [OPTIONS] COMMAND [ARGS]...
Error: Invalid value for "--token-file" / "-T": Could not open file: /not/existing/path: No such file or directory …
```
=> Add "--token-file" switch/option

CHANGELOG.md, vault_cli/requests.py
Exception was:
Traceback (most recent call last):
File "vault/bin/vault", line 11, in <module>
sys.exit(main())
File "vault/local/lib/python2.7/site-packages/vault_cli/vault.py", line 224, in main
return cli(default_map=config)
File "vault/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
return self.main(*args, **kwargs)
File "vault/local/lib/python2.7/site-packages/click/core.py", line 697, in main
rv = self.invoke(ctx)
File "vault/local/lib/python2.7/site-packages/click/core.py", line 1063, in invoke
Command.invoke(self, ctx)
File "vault/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "vault/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
return callback(*args, …
=> Fix Python 2 compatibility: use absolute imports

debian/README, debian/changelog, debian/control
I have used this changes to build a package for vault-cli 0.3.0 and
upload it to the stretch-peopledoc repository
=> Update debian's changelog and add README

setup.cfg
use
```
pip install 'vault-cli[sni]'
```
when using vault-cli with old OSes
=> Add extra dependencies "sni"

.gitignore, .travis.yml, requirements.txt, setup.cfg, tests/integration/test_integration.py, tests/unit/test_cli.py, tests/unit/test_client.py, tests/unit/test_clients.py, tests/unit/test_main.py, tests/unit/test_settings.py, tox.ini, vault_cli/__init__.py, vault_cli/__main__.py, vault_cli/cli.py, vault_cli/client.py, vault_cli/hvac.py, vault_cli/requests.py, vault_cli/settings.py, vault_cli/types.py
This PR:
- Introduces proper linting with flake8 (configured to play nice with Black)
- Adds black as an autoformatter
- Removes Python 2.7 in order to...
- ... Add(s) type hints and mypy everywhere
- Add isort (configured to play nice with black)
- Add support for Python 3.7
- Rework the tox integration
- And finally test all this in Travis
=> Linting, mypy etc

vault_cli/exceptions.py
Fix a typo: `s/autent/authent/`
=> Fix a typo: s/autent/authent/

CHANGELOG.md, README.md, setup.cfg, tests/unit/test_client.py, vault_cli/client.py
Allow to write secret when if `read` and/or `list` accesses are not allowed.
Using the below policy, `VaultForbidden` exception is raised because user don't have `list` access:
```
path "secret/testproject/secret" {
capabilities = ["read", "create", "update"]
}
```
Same exception occurs when:
- user is allowed to create and/or update a secret but not to read the related path
- user isn't allowed to read parent paths
=> Allow to write secret when if 'read' and/or 'list' accesses are not allowed

CHANGELOG.md, README.md, tests/unit/test_cli.py, tests/unit/test_client_base.py, tests/unit/test_settings.py, tests/unit/test_testing.py, vault_cli/cli.py, vault_cli/client.py, vault_cli/settings.py, vault_cli/testing.py
Based on #71 
This PR introduces `--safe-write`, which makes the previous introduction of `--force` a non-breaking change.
In the end, ``safe-write`` and ``--force`` are analogous, with opposite defaults, but it makes it easier to decide if you want to work with safe-write on or off in your config file, and then just use `--force` (which you can't set in your config file) when you need, or if you don't care.
Of course, we could still do that with a single argument but it would be quite less clear.
=> Safe write

CHANGELOG.md, README.md, tests/unit/test_cli.py, tests/unit/test_environment.py, vault_cli/cli.py, vault_cli/environment.py
Add possibility to customize environment variables names in `vault env`
using `--path path/to/keys=myprefix`
- If the path is not a folder the prefix value is used as the name of the
variable.
e.g.: for a/b/key, `--path a/b/c=foo` gives `FOO=...`
- If the path is a folder, then the variable names will be generated as:
`PREFIX + _ + relative path`
e.g.: for a/b/key, `--path a/b=my` gives `MY_KEY=...`
- The standard behavior has not changed and will generate variable names
as:
`relative path to the parent of the given path`
e.g.: for a/b/key, `--path a/b` gives `B_KEY=...`
Cf. #ticket-number
=> Customize environment variables names in vault env

tests/conftest.py, tests/integration/test_integration.py
Closes #88 
I can't see a way to properly isolate fs without multiplying the test suite time by more than 100.
=> Isolate tests from env vars

CHANGELOG.md, tests/integration/test_integration.py, tests/unit/test_cli.py, tests/unit/test_client_base.py, tests/unit/test_client_hvac.py, vault_cli/client.py, vault_cli/testing.py
Cf. #97 
vault-cli has been designed read and write all the values in a "value" key.
Here, if the secret does not contain a single "value" key, we return
directly the whole kv dict.
=> Add support for secrets not stored in a "value" key

CHANGELOG.md, tests/unit/test_client_hvac.py, vault_cli/client.py
It's much more easier to read when it's sorted :)
I can't reproduce the issue in my dev env, but using a postgres storage in production I had unsorted output.
Cf. #ticket-number
=> Sort the output of vault list

.gitignore, tests/unit/test_client_base.py, vault_cli/client.py
Fixes #102
- Add implicit caching (or "poor man's atomicity", if you prefer: in a single vault-cli call, each secret is never read more than once)
- Add explicit caching, via `with client.caching()`. Sadly, the vault cli lib is not documented, this is something to tackle someday
- Add recursive templates: as long as it's not an infinite recursion, templates will be rendered recursively.
- Fixes a small issue: now all calls will had a path with a leading `/`. This helps caching because it helps canonicalizing paths.
=>  Add implicit and explicit caching

CHANGELOG.md, tests/integration/test_integration.py, tests/unit/test_cli.py, tests/unit/test_client_base.py, vault_cli/cli.py, vault_cli/client.py
New output format where the keys of the yaml output are no more "merged"
into a tree but are kept as full path.
The new output is looks like:
```yaml
my/nested/path: string
my/nested/other_path:
key1: val1
key2: val2
```
=> Add a flat output to the get-all command

CHANGELOG.md, README.md, tests/integration/test_integration.py, tests/unit/test_cli.py, vault_cli/cli.py
Release 1.x introduces major changes in the API, we take this
opportunity to change the default output of `vault get-all` to the
"flat" version, that better differentiates between paths and mapping
values.
Cf. #ticket-number
=> Enable --flat by default on `vault get-all`

CHANGELOG.md, vault_cli/cli.py
the default output is stdout.
Cf. #ticket-number
=> Add `--output` option to `vault get`

CHANGELOG.md, tests/unit/test_client_base.py, vault_cli/client.py, vault_cli/testing.py
Co-Authored-By: Joachim Jablon<ewjoachim@gmail.com>
Cf. #135
=> Fixes #135 trailing slash in path issue in `get-all` and `delete-all`

setup.cfg
@mgu Honnestly I'm not sure if it's our responsibility or if we should use restriction only for the version that we break with. What's your call ?
=> PyYAML<5.3.1 has a CVE, we should really avoid it

docs/howto/environment.rst, tests/unit/test_cli.py, vault_cli/cli.py
- Use pathlib to write template
- Refactor the split by : and =
- vault env: --path is now --envvar but --path/-p is still accepted
- Add a clean error on invalid envvar format
=> Refactor vault-cli env, rename --path to --envvar (with compat)

docs/howto/permissions.rst, tests/integration/test_integration.py, tests/unit/test_cli.py, vault_cli/cli.py
=> Default umask to restrict permissions on file
