peopledoc/vault-cli

vault_cli/vault.py

Fix a typo

---

.gitignore
README.md
vault_cli/vault.py
vault_cli/vault_python_api.py

Various improvements including folder path in `get-all` and `list` command.
This fix also lists recursively the folders when calling `get-all` on a folder.

Vault CLI improvements

---

README.md
vault_cli/vault.py
vault_cli/vault_python_api.py

Add error handling for easing use.

Add error handling when calling the command

---

README.md
vault_cli/vault.py
vault_cli/vault_python_api.py

Take in account https://github.com/peopledoc/vault-cli/pull/6#discussion_r183255310

Use license in headers and documentation

---

setup.cfg

https://pypi.org/project/vault-cli/
https://github.com/peopledoc/vault-cli/releases/tag/0.3.0

Release 0.3.0

---

vault_cli/__init__.py
vault_cli/__main__.py
vault_cli/cli.py
vault_cli/client.py
vault_cli/hvac.py
vault_cli/requests.py
vault_cli/settings.py

Add Jacques Rott as contributor

---

setup.cfg

Needed for https://github.com/pallets/click/pull/874

Click version 7

---

README.md
tests/integration/test_integration.py
tests/unit/test_cli.py
tests/unit/test_client.py
vault_cli/cli.py
vault_cli/client.py

Closes #45
PR based on #46 , please merge that one first ! *EDIT* done ! thx
With this, one might be able to start loading secrets at process launch even if their vault doesn't offer high availablility yet.
Of course, saving secrets locally is sub-par, but any other solution would involve saving secrets locally one way or another, so at least this one is one step ahead in the future.

Closes #45 - Bootstrap env

---

CHANGELOG.md
README.md
tests/integration/test_integration.py
tests/unit/test_cli.py
tests/unit/test_client.py
tests/unit/test_clients.py
tests/unit/test_settings.py
tox.ini
vault_cli/cli.py
vault_cli/client.py
vault_cli/settings.py

@pilou- my take on #42 if you like it.
Ping @jacquesrott @yannlachiver 
Base on #47, rebase after merge.
Fixes #27

Dump config

---

CHANGELOG.md
README.md
tests/integration/test_integration.py
tests/unit/test_cli.py
tests/unit/test_client.py
vault_cli/cli.py
vault_cli/client.py

Closes #21
Based on #48, rebase after merge.

Closes #21, Delete all

---

README.md
tests/unit/test_cli.py
tests/unit/test_client.py
tests/unit/test_environment.py
tests/unit/test_utils.py
vault_cli/cli.py
vault_cli/client.py
vault_cli/environment.py
vault_cli/requests.py
vault_cli/utils.py

Addressing remarks from #47 implementing #45 
based on #49 
@mgu Is it ok for you ? Can we check back with our original usecase to make sure we didn't forget anything ?

Env dict keys

---

tests/unit/test_client.py
tests/unit/test_clients.py
vault_cli/client.py
vault_cli/hvac.py
vault_cli/requests.py
vault_cli/sessions.py

Close connection (Fixes #41)

---

CHANGELOG.md
setup.cfg

Anyone with review access, please merge it :) Tag has already been pushed, and release on PyPI was already made.

Release 0.4.0

---

README.md
setup.cfg
tests/unit/conftest.py
tests/unit/test_cli.py
tests/unit/test_fake.py
tests/unit/test_templates.py
vault_cli/__init__.py
vault_cli/__main__.py
vault_cli/cli.py
vault_cli/client.py
vault_cli/hvac.py
vault_cli/requests.py
vault_cli/settings.py
vault_cli/templates.py

Fixes #58 
Based on #57 
@pilou- when this is merged, we can remove almost all cases where ansible reads a secret from the vault (except secrets pertaining to specific deployment actions like slack tokens)
Ping @mgu @pmourlanne

Vault Template

---

README.md

Following the discussion on #62

Rework readme, add some examples.

---

tests/unit/conftest.py
tests/unit/test_cli.py
tests/unit/test_client.py
tests/unit/test_clients.py
tests/unit/test_settings.py
tests/unit/test_templates.py
vault_cli/__init__.py
vault_cli/cli.py
vault_cli/client.py
vault_cli/exceptions.py
vault_cli/hvac.py
vault_cli/requests.py
vault_cli/settings.py

Error handling

---

CHANGELOG.md
setup.cfg

Changelog ammended.
#74 tested and approved.

Release 0.6.0

---

CHANGELOG.md
README.md
tests/unit/test_cli.py
tests/unit/test_client_base.py
tests/unit/test_client_hvac.py
vault_cli/client.py

Relative vs absolute path

---

release

Various fixes in release script

---

CHANGELOG.md
README.md
tests/integration/test_integration.py
tests/unit/test_cli.py
vault_cli/cli.py

Closes #87 
Should be one of the last big bangs before 1.0

Use get --text by default

---

CHANGELOG.md
README.md
tests/unit/test_cli.py
vault_cli/cli.py

Prompt value with hidden input

---

CHANGELOG.md
tests/unit/test_settings.py
vault_cli/client.py
vault_cli/settings.py

Config file lib

---

CHANGELOG.md
tests/unit/test_client_base.py
vault_cli/client.py

Support templates when values are dict

---

CHANGELOG.md
README.md
tests/unit/test_cli.py
vault_cli/cli.py
vault_cli/client.py

add Jinja2 'include' support for template command

---

CHANGELOG.md
setup.cfg

Ping @weakcamel 
0.12.0 has been released and pushed to PyPI.

Release 0.12.0

---

CHANGELOG.md
setup.cfg
tests/unit/test_cli.py
tox.ini
vault_cli/cli.py

New lines 110

---

vault_cli/cli.py

Fix failing CI due to mypy and typeshed update

---

CHANGELOG.md
tests/unit/test_client_base.py
vault_cli/client.py

Fix vault get-all and vault env without list permission

---

CHANGELOG.md
README.md
tests/integration/test_integration.py
tests/unit/test_cli.py
tests/unit/test_client_base.py
tests/unit/test_client_hvac.py
tests/unit/test_environment.py
vault_cli/cli.py
vault_cli/client.py
vault_cli/environment.py
vault_cli/utils.py

Remove the hard-coded "value" key used in get/set

---

README-systemd.md
README.md

Add documentation for systemd integration strategies

---

CHANGELOG.md
setup.cfg

Release 1.0.0

---

CHANGELOG.md
tests/integration/test_integration.py
tests/unit/test_environment.py
vault_cli/cli.py
vault_cli/environment.py
vault_cli/exceptions.py

Omit special chars 138

---

CHANGELOG.md
setup.cfg
tests/conftest.py
tests/integration/test_integration.py
tests/unit/test_cli.py
tests/unit/test_environment.py
tests/unit/test_ssh.py
vault_cli/cli.py
vault_cli/environment.py
vault_cli/ssh.py

Add vault ssh

---

.github/PULL_REQUEST_TEMPLATE.md

Pull request template mentions doc

---

docs/howto/templated_secrets.rst

Adding documentation regarding templated secrets and Ansible Jinja2 + Yaml

Templated secrets and ansible

---

docs/discussions.rst

Fixing markup

---

docs/discussions.rst
docs/howto/template.rst
docs/howto/templated_secrets.rst

Documentation for vault-cli template

---

CHANGELOG.rst
CONTRIBUTING.rst
README.rst
docs/discussions.rst
docs/howto/base_path.rst
docs/howto/configure.rst
docs/howto/environment.rst
docs/howto/lookup.rst
docs/howto/organize.rst
docs/howto/read.rst
docs/howto/secret_with_dash.rst
docs/howto/systemd.rst
docs/howto/template.rst
docs/howto/templated_secrets.rst
docs/howto/upgrade.rst
docs/howto/write.rst
docs/quickstart.rst
setup.cfg
tests/integration/test_integration.py
vault_cli/cli.py

Fixes #89 - Rename vault as vault-cli (with compat)

---

docs/howto/organize.rst
docs/howto/safe_write.rst

Documentation: Reorganize secrets

---

docs/index.rst

Add manual page in the main documentation

---

docs/howto/ssh.rst
docs/howto/template.rst

Vault ssh documentation

---

docs/discussions.rst
docs/howto/configure.rst
docs/quickstart.rst
docs/quickstart_demo.py

Documentation: Quickstart

---

docs/howto/read.rst
docs/howto/systemd.rst

Documentation: Read secrets

---

CHANGELOG.rst
release
setup.cfg

Release 1.3.0

---

docs/howto/test.rst

Fix doc regarding testing

---

CHANGELOG.rst
setup.cfg

Release 1.3.1

---

.github/PULL_REQUEST_TEMPLATE.md

Closes nothing
- Nothing applicable

Fix PULL_REQUEST_TEMPLATE.md

---

CHANGELOG.rst
docs/howto/permissions.rst
docs/howto_index.rst
tests/integration/test_integration.py
tests/unit/test_cli.py
vault_cli/cli.py
vault_cli/types.py

Closes #162
Paired with @SBillion @elemoine @entwanne ! (what email shall I use for co-authored-by ?)

Add --umask option #162

---

CHANGELOG.rst
tests/integration/test_integration.py
tests/unit/test_cli.py
tests/unit/test_ssh.py
vault_cli/cli.py
vault_cli/exceptions.py
vault_cli/ssh.py

Closes #167
Note : l'option -q est disponible à partir de OpenSSH_7.9p1

Do not see ssh-add message

---

docs/howto/environment.rst

Fix broken markup

---

docs/howto/templated_secrets.rst

Improve a doc title wording

---

docs/howto/environment.rst
tests/unit/test_cli.py
tests/unit/test_client_base.py
tests/unit/test_client_hvac.py
tests/unit/test_exceptions.py
vault_cli/cli.py
vault_cli/client.py
vault_cli/environment.py
vault_cli/exceptions.py
vault_cli/utils.py

Crash consistently, or not crash consistently on vault-cli env

---

.github/workflows/deploy.yml
pyproject.toml
setup.cfg
tests/unit/test_metadata.py

We were missing half of the code for automated releases :/

Fix automated release

---

.github/workflows/ci.yml

Run CI on PRs based on forks

---

docs/howto/organize.rst
tests/unit/test_cli.py
tests/unit/test_client_base.py
vault_cli/cli.py
vault_cli/client.py

Closes #119 
---
Needed this option, ran into your utility, and discovered it was missing. 
It's almost the first time I code something using python, don't hesitate to tell me if something is wrong! :slightly_smiling_face:

implemented a cp function

---

.github/workflows/ci.yml

CI on both PRs and the master branch

---

docs/howto/import_export.rst
docs/howto/write.rst
docs/howto_index.rst
setup.cfg
tests/unit/test_cli.py
tests/unit/test_client_base.py
tests/unit/test_exceptions.py
vault_cli/cli.py
vault_cli/client.py
vault_cli/exceptions.py
vault_cli/metadata.py
vault_cli/sessions.py

vault-cli set-all

---

.github/CODEOWNERS

Goodbye Mickaël - Remove @mgu from codeowners

---

.github/CODEOWNERS

Note: the rule "codeowners needs to review" was disabled. Not sure we should re-enable it.

Add @elemoine to CODEOWNERS

---

.github/CODEOWNERS

Remove Eric from codeowners

---

tests/unit/test_client_base.py
vault_cli/client.py

Use a sandbox environment for Jinja

---

docs/quickstart.rst

Fix docker run command, -p instead of --port

---

setup.cfg
tests/unit/test_metadata.py

Switching author email to community
